### ISSUE TITLE
Getting 404 not found error when installing via NPM

### ISSUE THREAD

**Issue by sudharsan1988** [hemanth/react-currency-conversion#67]
Here is the error log when I try to install it via npm,

npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save" "react-exchange-rate"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/react-exchange-rate
npm ERR! 404 
npm ERR! 404  'react-exchange-rate' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sith/reactJs/este/este-app/npm-debug.log

**Comment by hemanth** [comment]
Try `react-currency-conversion`
